export const SCHOOL_INFO = {
  name: "Sevasi High School",
  nameGujarati: "સેવાસી હાઈ સ્કૂલ",
  location: "Sewasi, Vadodara, Gujarat",
  locationGujarati: "સેવાસી, વડોદરા, ગુજરાત",
  medium: "Gujarati Medium",
  mediumGujarati: "ગુજરાતી માધ્યમ",
  board: "State Board (GSEB)",
  boardGujarati: "રાજ્ય બોર્ડ (GSEB)",
  grades: "Primary, Secondary, Higher Secondary",
  gradesGujarati: "પ્રાથમિક, માધ્યમિક, ઉચ્ચતર માધ્યમિક",
  established: "1967",
  rating: "3.9",
  reviewCount: "22",
  phone: "+91 98765 43210",
  email: "info@sevasihighschool.edu.in",
  address: "સેવાસી, વડોદરા, ગુજરાત - 391101",
  addressEn: "Sewasi, Vadodara, Gujarat - 391101",
  paymentModes: "Cheque / Demand Draft, Cash",
  paymentModesGujarati: "ચેક / ડિમાન્ડ ડ્રાફ્ટ, રોકડ",
  officeHours: {
    weekdays: "7:00 AM – 6:00 PM",
    weekdaysGujarati: "સવારે ૭:૦૦ – સાંજે ૬:૦૦",
    saturday: "7:00 AM – 6:00 PM",
    saturdayGujarati: "સવારે ૭:૦૦ – સાંજે ૬:૦૦",
    sunday: "Closed",
    sundayGujarati: "બંધ",
  },
} as const;

export const NAV_ITEMS = [
  { label: "હોમ", labelEn: "Home", href: "/" },
  { label: "અમારા વિશે", labelEn: "About Us", href: "/about" },
  { label: "શૈક્ષણિક", labelEn: "Academics", href: "/academics" },
  { label: "પ્રવેશ", labelEn: "Admissions", href: "/admissions" },
  { label: "વિદ્યાર્થી જીવન", labelEn: "Student Life", href: "/student-life" },
  { label: "સંપર્ક", labelEn: "Contact", href: "/contact" },
] as const;
